# Generated by Django 3.0.4 on 2020-03-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0003_auto_20200325_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
