# Generated by Django 3.0.4 on 2020-03-31 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0004_seat_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ['priority']},
        ),
    ]
