# Generated by Django 3.0.4 on 2020-03-31 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0005_auto_20200331_1216'),
        ('votes', '0004_auto_20200328_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservote',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='elections.Election'),
        ),
    ]
