# Generated by Django 3.0.4 on 2020-03-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('elections', '0001_initial'), ('elections', '0002_auto_20200325_1216')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('start_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
