# Generated by Django 3.0.4 on 2020-03-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='active',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
