# Generated by Django 3.0.4 on 2020-03-25 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_squashed_0002_auto_20200325_1216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='election',
            options={'get_latest_by': 'end_date'},
        ),
    ]
