# Generated by Django 3.0.4 on 2020-04-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0005_auto_20200331_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='slug',
            field=models.SlugField(editable=False, null=True),
        ),
    ]
