# Generated by Django 3.0.4 on 2020-04-04 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0006_election_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
