# Generated by Django 3.0.4 on 2020-03-22 21:25

from django.db import migrations, models
import django.db.models.deletion
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('image', pyuploadcare.dj.models.ImageField()),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='seats.Seat')),
            ],
        ),
    ]
