# Generated by Django 3.0.4 on 2020-03-27 05:12

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='image',
            field=pyuploadcare.dj.models.ImageField(null=True),
        ),
    ]
