# Generated by Django 3.0.4 on 2020-03-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_auto_20200327_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
