# Generated by Django 3.0.4 on 2020-03-29 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_candidate_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='priority',
        ),
    ]
