# Generated by Django 3.1.1 on 2020-10-20 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0003_auto_20201015_1451'),
        ('campaigns', '0006_campaignprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=50, null=True)),
                ('donor_phone', models.CharField(max_length=15)),
                ('donor_email', models.EmailField(max_length=254, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
            ],
        ),
        migrations.CreateModel(
            name='DonationProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='donations.donation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaignproduct')),
            ],
        ),
    ]
