# Generated by Django 3.1.1 on 2020-10-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_campaignprofile'),
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='donationproduct',
            unique_together={('donation', 'product')},
        ),
    ]
