# Generated by Django 3.2.5 on 2022-04-30 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('donations', '0002_auto_20210802_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.campaign'),
        ),
    ]
