# Generated by Django 3.1.1 on 2020-11-05 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20201015_1451'),
        ('donations', '0004_donationproduct_delivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.cart'),
        ),
    ]
