# Generated by Django 3.1.1 on 2020-11-11 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_auto_20201105_0606'),
        ('donations', '0005_auto_20201105_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_products', to='campaigns.campaignproduct'),
        ),
    ]
