# Generated by Django 3.1.1 on 2020-09-28 17:59

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='image',
            field=pyuploadcare.dj.models.ImageField(null=True),
        ),
    ]
