# Generated by Django 3.1.1 on 2020-09-30 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_auto_20200928_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignproduct',
            name='target',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
