# Generated by Django 3.1.1 on 2020-10-03 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201003_0557'),
        ('campaigns', '0004_campaign_deleted'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campaignproduct',
            unique_together={('campaign', 'product')},
        ),
    ]
