# Generated by Django 3.1.1 on 2020-12-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_productrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
