# Generated by Django 3.1.1 on 2020-10-15 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_campaignprofile'),
        ('cart', '0002_auto_20201007_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_products', to='campaigns.campaignproduct'),
        ),
    ]
