# Generated by Django 3.1.1 on 2020-11-17 09:27

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_form',
            field=pyuploadcare.dj.models.FileField(null=True),
        ),
    ]
