# Generated by Django 3.1.1 on 2020-11-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_delivery_delivery_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('delivered', 'Delivered')], default='pending', max_length=10),
        ),
    ]
